name: monorepo

packages:
    - apps/**
    - packages/**

command:
    version:
        branch: main
        releaseUrl: true

scripts:
    analyze:
        exec: dart analyze .
    format:
        exec: dart format . --fix
